### PR TITLE
Add border radius

### PR DESCRIPTION
**Pull request by jte0711**
- Adding borderRadius as an optional style.

### CODE REVIEW

**Comment by natysoz** [comment]
@jte0711 sorry i forgot to push my last version the conflicts are just in package json i believe

**Comment by jte0711** [comment]
@jte0711 updated the PR

**Comment by natysoz** [comment]
can we update also README so ppl may know about this new 1 ?

**Comment by jte0711** [comment]
@natysoz yes, done. let me know if there's anything else

**Pull request merged**
