### PR TITLE
Add mediaType to modAssets and fix the type following the changes

### LINKED ISSUE #33: Add mediaType to the result of resized image
hey guys, great work on the library. 

- **Proposed change:**
I think it would be great to add mediaTypes to the result of resizedImage

The reason is whenever we passed the widgetResize, it will only return `width`, `height`, `uri`, and possibly `base64` if user set it to true and all of the initial data from the asset such as `mediaType`, `filename`, etc are omitted from the response. It would be great to include some of them which still relevant to the data to the `resizedImage` response. 

I already have code ready, if you guys okay with it I can create a PR for it.

### PR DESCRIPTION
**Pull request by jte0711**
Resolve #33

### CODE REVIEW

**Comment by jte0711** [comment]
hey @natysoz , is there anything you want me to add in this PR?

**Comment by natysoz** [comment]
see if u can update your PR so i can merge it

**Comment by jte0711** [comment]
@natysoz which part of it do you want me to update? I don't see any conflict for the branch

**Comment by natysoz** [comment]
@jte0711 sorry i forgot to push my last version the conflicts are just in package json i believe

**Comment by jte0711** [comment]
@natysoz no worries, I updated the PR

**Comment by natysoz** [comment]
can u also add this to readme and changelog please ?

**Comment by jte0711** [comment]
@natysoz Done, I updated the changelog. There's no documentation on what the component will return in the readme so I don't see where I should write down my changes.

**Comment by natysoz** [comment]
before merging , 1 question

what is the difference between the image type we get back 
from the image type we are converting into ?

` const widgetResize = useMemo(
        () => ({
            width: 512,
            compress: 0.7,
            base64: false,
            saveTo: 'jpeg'
        }),
        []
    )
`

at that point i know that all images will return as image/jpeg so why do we need to add it back inside the images object?

we cant just add it if necessary inside our component or state before uploading ?

**Comment by jte0711** [comment]
> what is the difference between the image type we get back from the image type we are converting into ?
> 
> `const widgetResize = useMemo( () => ({ width: 512, compress: 0.7, base64: false, saveTo: 'jpeg' }), [] )`
> 
> at that point i know that all images will return as image/jpeg so why do we need to add it back inside the images object?

yea that's true, but user's gallery is a mix of `photo`, `video`, and other `mediaType` so we need it to specify which `mediaType` the file is. 

I know we can just detect it from the filename, but then it will be so inconsistent. Here is the type of data we normally return 

```
export declare type Asset = {
    id: string;
    filename: string;
    uri: string;
    mediaType: MediaTypeValue;
    mediaSubtypes?: string[];
    width: number;
    height: number;
    creationTime: number;
    modificationTime: number;
    duration: number;
    albumId?: string;
};
```

Here is the type of data returned for resized image:

```
export declare type ImageResult = {
    uri: string;
    width: number;
    height: number;
    base64?: string;
};
```

so adding `mediaType` will help at least to show what's the type of the file.

**Comment by natysoz** [comment]
fix conflicts ill merge

**Comment by jte0711** [comment]
> fix conflicts ill merge

Ok, I just did it.

**Pull request merged**
